//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql2ExcelExporterUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sql2ExcelExporterUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string CW_CANCEL_BUTTON_CONTENT {
            get {
                return ResourceManager.GetString("CW_CANCEL_BUTTON_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string CW_OK_BUTTON_CONTENT {
            get {
                return ResourceManager.GetString("CW_OK_BUTTON_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Database ähnelt.
        /// </summary>
        public static string DBCW_TITLE {
            get {
                return ResourceManager.GetString("DBCW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... ähnelt.
        /// </summary>
        public static string MW_ASSIST_BUTTON_CONTENT {
            get {
                return ResourceManager.GetString("MW_ASSIST_BUTTON_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Columns: ähnelt.
        /// </summary>
        public static string MW_COLUMNS_LABEL {
            get {
                return ResourceManager.GetString("MW_COLUMNS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Excel File ähnelt.
        /// </summary>
        public static string MW_CREATE_EXCEL_FILE_BUTTON_CONTENT {
            get {
                return ResourceManager.GetString("MW_CREATE_EXCEL_FILE_BUTTON_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database: ähnelt.
        /// </summary>
        public static string MW_DATABASE_LABEL {
            get {
                return ResourceManager.GetString("MW_DATABASE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory: ähnelt.
        /// </summary>
        public static string MW_DIRECTORY_LABEL {
            get {
                return ResourceManager.GetString("MW_DIRECTORY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No directory specified ähnelt.
        /// </summary>
        public static string MW_ERROR_MISSING_DIRECTORY {
            get {
                return ResourceManager.GetString("MW_ERROR_MISSING_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No table specified ähnelt.
        /// </summary>
        public static string MW_ERROR_MISSING_TABLE {
            get {
                return ResourceManager.GetString("MW_ERROR_MISSING_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No columns selected ähnelt.
        /// </summary>
        public static string MW_ERROR_NO_COLUMNS_SELECTED {
            get {
                return ResourceManager.GetString("MW_ERROR_NO_COLUMNS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Header Style ähnelt.
        /// </summary>
        public static string MW_HEADER_STYLE_LABEL {
            get {
                return ResourceManager.GetString("MW_HEADER_STYLE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bold ähnelt.
        /// </summary>
        public static string MW_HS_BOLD_LABEL {
            get {
                return ResourceManager.GetString("MW_HS_BOLD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font Size ähnelt.
        /// </summary>
        public static string MW_HS_FONT_SIZE_LABEL {
            get {
                return ResourceManager.GetString("MW_HS_FONT_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italic ähnelt.
        /// </summary>
        public static string MW_HS_ITALIC_LABEL {
            get {
                return ResourceManager.GetString("MW_HS_ITALIC_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Underline ähnelt.
        /// </summary>
        public static string MW_HS_UNDERLINE_LABEL {
            get {
                return ResourceManager.GetString("MW_HS_UNDERLINE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File &quot;{FILE_PATH}&quot; created ähnelt.
        /// </summary>
        public static string MW_INFO_FILE_CREATED {
            get {
                return ResourceManager.GetString("MW_INFO_FILE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string MW_INFO_TITLE {
            get {
                return ResourceManager.GetString("MW_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        public static string MW_SELECT_ALL_TABLES_BUTTON_CONTENT {
            get {
                return ResourceManager.GetString("MW_SELECT_ALL_TABLES_BUTTON_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select None ähnelt.
        /// </summary>
        public static string MW_SELECT_NONE_TABLES_BUTTON_CONTENT {
            get {
                return ResourceManager.GetString("MW_SELECT_NONE_TABLES_BUTTON_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server: ähnelt.
        /// </summary>
        public static string MW_SERVER_LABEL {
            get {
                return ResourceManager.GetString("MW_SERVER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table: ähnelt.
        /// </summary>
        public static string MW_TABLE_LABEL {
            get {
                return ResourceManager.GetString("MW_TABLE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQL 2 Excel Exporter ähnelt.
        /// </summary>
        public static string MW_TITLE {
            get {
                return ResourceManager.GetString("MW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string MW_TLV_HEADER_NAME {
            get {
                return ResourceManager.GetString("MW_TLV_HEADER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected ähnelt.
        /// </summary>
        public static string MW_TLV_HEADER_SELECTED {
            get {
                return ResourceManager.GetString("MW_TLV_HEADER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supported ähnelt.
        /// </summary>
        public static string MW_TLV_HEADER_SUPPORTED {
            get {
                return ResourceManager.GetString("MW_TLV_HEADER_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string MW_TLV_HEADER_TYPE {
            get {
                return ResourceManager.GetString("MW_TLV_HEADER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Table ähnelt.
        /// </summary>
        public static string TCW_TITLE {
            get {
                return ResourceManager.GetString("TCW_TITLE", resourceCulture);
            }
        }
    }
}
